steps:
  - name: 'gcr.io/cloud-builders/docker'
    dir: 'app1'  # Pastikan untuk menetapkan direktori konteks build
    args: ['build', '-t', 'gcr.io/p3tcc-417606/app1', '.']
  - name: 'gcr.io/cloud-builders/docker'
    dir: 'app1'
    args: ['push', 'gcr.io/p3tcc-417606/app1']
  - name: 'gcr.io/google-cloud-sdk'
    entrypoint: gcloud
    args: ['run', 'deploy', 'app1', '--image', 'gcr.io/p3tcc-417606/app1', '--region', 'us-central1', '--platform', 'managed', '--allow-unauthenticated', '--cpu', '1']

images:
  - 'gcr.io/p3tcc-417606/app1'

options:
  logging: CLOUD_LOGGING_ONLY
