steps:
  - name: 'gcr.io/cloud-builders/docker'
    dir: 'app2'  # Pastikan untuk menetapkan direktori konteks build
    args: ['build', '-t', 'gcr.io/p3tcc-417606/app2', '.']
  - name: 'gcr.io/cloud-builders/docker'
    dir: 'app2'
    args: ['push', 'gcr.io/p3tcc-417606/app2']
  - name: 'gcr.io/google-cloud-sdk'
    entrypoint: gcloud
args: ['run', 'deploy', 'app2', '--image', 'gcr.io/p3tcc-417606/app1', '--region', 'us-central1', '--platform', 'managed', '--allow-unauthenticated', '--cpu', '1', '--verbosity=debug']

images:
  - 'gcr.io/p3tcc-417606/app2'

options:
  logging: CLOUD_LOGGING_ONLY
